# Makefile generated by Make My File: https://github.com/MathysCogne/Make_My_File-42
# Date of generation: 09-11-2024 21:34:51

NAME = push_swap

SRCDIR = src
OBJDIR = obj
INCDIR = include

SRC = main.c \
		push_swap.c \
			parsing.c \
			sort/sort_dispatcher.c sort/sort_three.c sort/sort_five.c \
			sort/block_sort/block_sort.c sort/block_sort/phase_1.c sort/block_sort/phase_2.c  sort/block_sort/sort_utils.c \
			operation/swap.c operation/push.c operation/rotate.c operation/reverse_rotate.c \
			utils/utils.c utils/utils_lst.c utils/find_pos.c utils/already_sort.c

OBJ = $(SRC:.c=.o)
SRC := $(addprefix $(SRCDIR)/, $(SRC))
OBJ := $(patsubst $(SRCDIR)/%, $(OBJDIR)/%, $(OBJ))



NAME_BONUS = checker

SRC_BONUS =	checker_bonus/checker_bonus.c \
				checker_bonus/read_make_operation_bonus.c \
				checker_bonus/operation_bonus/swap_bonus.c checker_bonus/operation_bonus/push_bonus.c checker_bonus/operation_bonus/rotate_bonus.c checker_bonus/operation_bonus/reverse_rotate_bonus.c \
				parsing.c utils/utils.c utils/utils_lst.c utils/find_pos.c utils/already_sort.c \

OBJ_BONUS = $(SRC_BONUS:.c=.o)
SRC_BONUS := $(addprefix $(SRCDIR)/, $(SRC_BONUS))
OBJ_BONUS := $(patsubst $(SRCDIR)/%, $(OBJDIR)/%, $(OBJ_BONUS))


# Libraries
LIBFT_DIR := libft
LIBFT := $(LIBFT_DIR)/libft.a
LIBFT_INCLUDE := $(LIBFT_DIR)/include

LDFLAGS =  -L$(LIBFT_DIR)
LIBS =  $(LIBFT)

# Compiler and Flags
CC = cc
CFLAGS = -Wall -Wextra -Werror -I$(INCDIR) -g3 -I$(LIBFT_INCLUDE)

# Compilation mode (silent by default, set VERBOSE=1 to show commands)
VERBOSE ?= 0
ifeq ($(VERBOSE),1)
  V := 
else
  V := @
endif

# Colors
RED     := "\033[1;31m"
GREEN   := "\033[1;32m"
RESET   := "\033[0m"



#########################################
#	Default								#
#########################################

all: $(OBJDIR) $(LIBFT) $(NAME)

$(OBJDIR):
	$(V)mkdir -p $(OBJDIR) || true

DEP = $(OBJ:.o=.d)

$(OBJDIR)/%.o: $(SRCDIR)/%.c | $(OBJDIR)
	@mkdir -p $(dir $@)
	$(V)$(CC) $(CFLAGS) -MMD -MP -c $< -o $@

-include $(DEP)

$(NAME): $(OBJ) $(LIBFT)
	$(V)$(CC) $(CFLAGS) $(LDFLAGS) $(OBJ) $(BONUS_OBJ) $(LIBS) $(MLXFLAGS) -o $(NAME)
	$(V)echo $(GREEN)"[$(NAME)] Executable created ✅"$(RESET)


#########################################
#	Bonus								#
#########################################

bonus: $(OBJDIR) $(LIBFT) $(NAME_BONUS)

$(NAME_BONUS): $(OBJ_BONUS) $(LIBFT)
	$(V)$(CC) $(CFLAGS) $(LDFLAGS) $(OBJ_BONUS) $(LIBS) -o $@
	$(V)echo $(GREEN)"[$(NAME_BONUS)] Executable created ✅"$(RESET)

$(OBJDIR)/%.o: $(SRCDIR)/%.c | $(OBJDIR)
	@mkdir -p $(dir $@)
	$(V)$(CC) $(CFLAGS) -MMD -MP -c $< -o $@

DEP_BONUS = $(OBJ_BONUS:.o=.d)

-include $(DEP_BONUS)



# Libft - Branch 'V.push_swap_06_12_2024' (No Update before push projet)
$(LIBFT):
	$(V)echo '[$(NAME)] Downloading my Libft from github.com...'$(RESET)
	@git clone --branch V.push_swap_06_12_2024 https://github.com/MathysCogne/MyLibft_GNL_Printf.git libft > /dev/null 2>&1
	$(V)echo '[$(NAME)] Compiling Libft...'$(RESET)
	$(V)$(MAKE) --silent -C $(LIBFT_DIR)
	$(V)echo '[$(NAME)] Libft build successfully'

# Clean Rules
clean:
	$(V)echo $(RED)'[$(NAME)] Cleaning objects'$(RESET)
	$(V)rm -rf $(OBJDIR)

fclean: clean
	$(V)echo $(RED)'[$(NAME)] Cleaning all files'$(RESET)
	$(V)rm -f $(NAME)
	$(V)rm -f $(NAME_BONUS)
	$(V)$(MAKE) --silent -C $(LIBFT_DIR) fclean
	$(V)echo $(RED)'[libft] Remove directory'$(RESET)
	@rm -rf $(LIBFT_DIR)

re: fclean all

# Makefile Reconfiguration 
regen:
	makemyfile

.PHONY: all clean fclean re bonus regen
.DEFAULT_GOAL := all
